### ISSUE TITLE
Change Transaction entity parameters? 

### ISSUE THREAD

**Issue by AngelChen09** [StockSim/StockSim#57]
With the added company and industry stock data, we would also need to display it on the transaction history page. That would require additional data to be passed through (company and industry) but a better method is to just pass in the stock itself. 

Before:
transaction(timestamp, ticker, quantity, price, type)

After:
transaction(timestamp, stock, type)

Issue:
- Would any sell cases find this problematic based on their method on implementation? (i.e. stock is 'deleted' and cannot pass through information)

**Comment by ivorkchan** [comment]
While there're some new attributes for `Stock`, I don't think all of them need to be displayed on the transaction view page. User should care more about the time, ticker, quantity, and price then the transaction was made?
